CREATE DATABASE QUANLYKHACHSAN
USE QUANLYKHACHSAN

drop database QUANLYKHACHSAN
use temp

SET DATEFORMAT DMY

--1
CREATE TABLE LOAIPHONG
(
	MaLoaiPhong VARCHAR(10) NOT NULL CONSTRAINT PKLOAIPHONG PRIMARY KEY,
	DonGia MONEY
)


--2
CREATE TABLE PHONG
(
	MaPhong VARCHAR(10) NOT NULL CONSTRAINT PKPHONG PRIMARY KEY,
	MaLoaiPhong VARCHAR(10) CONSTRAINT FKPHONGLOAIPHONG FOREIGN KEY (MaLoaiPhong) REFERENCES LOAIPHONG(MaLoaiPhong) ON DELETE CASCADE,
	TinhTrangPhong BIT,
	GhiChu NVARCHAR(50)
)

--3
CREATE TABLE LOAIKHACHHANG
(
	MaLoaiKhachHang VARCHAR(10) NOT NULL CONSTRAINT PKLOAIKHACHHANG PRIMARY KEY,
	TenLoaiKhachHang NVARCHAR(50)
)

--4
CREATE TABLE PHIEUTHUEPHONG
(
	MaPhieuThue VARCHAR(10) NOT NULL CONSTRAINT PKPHIEUTHUEPHONG PRIMARY KEY,
	MaPhong VARCHAR(10) CONSTRAINT FKPHIEUTHUEPHONGPHONG FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong) ON DELETE CASCADE,
	NgayThue SMALLDATETIME,
	DonGia MONEY
)

--5
CREATE TABLE CHITIETPHIEUTHUE
(
	MaChiTietPhieuThue VARCHAR(10) NOT NULL CONSTRAINT PKCHITIETPHIEUTHUE PRIMARY KEY,
	MaPhieuThue VARCHAR(10) CONSTRAINT FKCHITIETPTPHIEUTHUE FOREIGN KEY (MaPhieuThue) REFERENCES PHIEUTHUEPHONG(MaPhieuThue) ON DELETE CASCADE,
	MaLoaiKhachHang VARCHAR(10) CONSTRAINT FKCHITIETPTLOAIKHACHHANG FOREIGN KEY (MaLoaiKhachHang) REFERENCES LOAIKHACHHANG(MaLoaiKhachHang) ON DELETE CASCADE,
	TenKhachHang NVARCHAR(50),
	CMND VARCHAR(20),
	DiaChi NVARCHAR(50)
)

--6
CREATE TABLE HOADON
(
	MaHoaDon VARCHAR(10) NOT NULL CONSTRAINT PKHOADON PRIMARY KEY,
	NgayThanhToan SMALLDATETIME,
	TenKhachHang NVARCHAR(50),
	DiaChi NVARCHAR(50),
	TongChiTietThanhToan MONEY  -- = TONG CAC THANH TIEN TRONG CHI TIET HOA DON
)

--7
CREATE TABLE CHITIETHOADON
(
	MaHoaDon VARCHAR(10) NOT NULL CONSTRAINT FKCHITIETHOADONHOADON FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon) ON DELETE CASCADE,
	MaPhieuThue VARCHAR(10) NOT NULL CONSTRAINT FKCHITIETHOADONPHIEUTHUEPHONG FOREIGN KEY (MaPhieuThue) REFERENCES PHIEUTHUEPHONG(MaPhieuThue) ON DELETE CASCADE,
	SoNgayThue INT,
	DonGia MONEY,
	ThanhTien MONEY,
	CONSTRAINT PKCHITIETHOADON PRIMARY KEY (MaHoaDon, MaPhieuThue)
)

--8
CREATE TABLE BAOCAO
(
	MaBaoCao VARCHAR(10) NOT NULL CONSTRAINT PKBAOCAO PRIMARY KEY,
	Thang INT NOT NULL,
	Nam INT NOT NULL,
	TongDoanhThu MONEY
)

--9
CREATE TABLE CHITIETBAOCAO
(
	MaBaoCao VARCHAR(10) CONSTRAINT FKCHITIETBAOCAOBAOCAO FOREIGN KEY (MaBaoCao) REFERENCES BAOCAO(MaBaoCao) ON DELETE CASCADE,
	MaLoaiPhong VARCHAR(10) CONSTRAINT FKCHITIETBAOCAOLOAIPHONG FOREIGN KEY (MaLoaiPhong) REFERENCES LOAIPHONG(MaLoaiPhong) ON DELETE CASCADE,
	DoanhThu MONEY,
	TiLe FLOAT,
	CONSTRAINT PKCHITIETBAOCAO PRIMARY KEY (MaBaoCao, MaLoaiPhong)
)

--10
CREATE TABLE THAMSO
(
	STT INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	HeSoPhuThu FLOAT,
	SoKhachToiDa TINYINT,
	SoKhachKhongTinhPhuThu TINYINT,
	TiLePhuThu FLOAT,
)

--create database temp use temp
drop Database QUANLYKHACHSAN

select * from LOAIPHONG
Select MaPhong,PHONG.MaLoaiPhong,TinhTrangPhong,DonGia From PHONG JOIN LOAIPHONG ON PHONG.MaLoaiPhong=LOAIPHONG.MaLoaiPhong Where PHONG.MaPhong = '01';

select MaPhong,PHONG.MaLoaiPhong,DonGia,TinhTrangPhong,GhiChu from PHONG join LOAIPHONG ON PHONG.MaLoaiPhong = LOAIPHONG.MaLoaiPhong

select MaPhong,PHONG.MaLoaiPhong,DonGia,TinhTrangPhong,GhiChu from PHONG join LOAIPHONG ON PHONG.MaLoaiPhong = LOAIPHONG.MaLoaiPhong

select * from PHONG
select * from LOAIPHONG

Select MaPhong,PHONG.MaLoaiPhong,DonGia,TinhTrangPhong,GhiChu into A From PHONG join LOAIPHONG ON PHONG.MaLoaiPhong = LOAIPHONG.MaLoaiPhong AND 

